== Introduction to demo application

Now that we've successfully deployed our cluster, and became a little more familiar with it we can deploy our application on it.
This application will allow us to become more familiar with some of the features of OpenShift/Kubernetes.

=== What will we do with the application?

In this lab, you'll go through a set of tasks that will help you understand the concepts of deploying and using container based applications.

Some of the things you'll be going through:

* Explore logging
* Experience self healing of applications
* Explore configuration management through configmaps, secrets and environment variables
* Use persistent storage to share data across pod restarts
* Explore networking within Kubernetes and applications
* Familiarization with OpenShift and Kubernetes functionality
* Use the ACK to deploy an S3 bucket which we will integrate with our application to upload and read files from it

You'll be doing the majority of the labs using the OpenShift CLI, but you can also accomplish them using the OpenShift web console.
