= Overview

https://aws.amazon.com/rosa/[Red Hat OpenShift Service on AWS] (ROSA) is a fully managed Red Hat OpenShift service in AWS that is jointly offered and supported by AWS and Red Hat. In this lab, you'll go through a set of tasks that will help you understand some of the concepts of deploying and securing container based applications on top of ROSA.

You can use this guide as an OpenShift tutorial and as study material to help you get started to learn OpenShift and integrating applications with AWS. The lab does touch on some basic Kubernetes concepts but does not go into detail explaining them as there is an expectation of a working knowledge of Kubernetes/OpenShift to do this lab.

.Some of the things you'll be going through:
* Experience self healing of applications
* Explore configuration management through configmaps, secrets and environment variables
* Explore networking within Kubernetes and applications
* Explore logging

Lastly, to tie it together in a real world scenario you will integrate the application with AWS S3 Storage and use https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html[IAM Roles for Service Accounts] (IRSA) to manage authentication and credentials to the service. Then the application will use that in order to read/write objects to AWS S3.

You'll be doing the majority of the labs using the OpenShift CLI, but you can also accomplish them using the Red Hat OpenShift web console as well.
