= Configure Log Forwarding to AWS CloudWatch

Red Hat OpenShift Service on AWS (ROSA) clusters store log data inside the cluster by default.
You also have the ability to use the provided tooling to forward your cluster logs to various locations, including https://aws.amazon.com/cloudwatch/[AWS CloudWatch].

In this section of the workshop, we'll configure ROSA to forward logs to AWS CloudWatch.

== Prepare AWS CloudWatch

Configuring ROSA to send logs to CloudWatch is not covered in this lab, as it goes beyond the lab's scope. However, integrating with AWS and enabling CloudWatch logging is an important aspect of ROSA's integration with AWS, so a script has been included to simplify the configuration process. The script will automatically set up AWS CloudWatch for later use in the lab. If you're interested, you can examine the script to understand the steps involved.

. Run the following script to configure your ROSA cluster to forward logs to CloudWatch.
+
[source,sh,role=execute]
----
curl -s https://raw.githubusercontent.com/openshift-cs/rosaworkshop/master/rosa-workshop/ostoy/resources/configure-cloudwatch.sh | bash
----
+
.Sample Output
[source,text,options=nowrap]
----
subscription.operators.coreos.com/cluster-logging created
Waiting for deployment to complete...
secret/cloudwatch-credentials created
clusterlogforwarder.logging.openshift.io/instance created
clusterlogging.logging.openshift.io/instance created
Complete.
----

. After a few minutes, you should begin to see log groups inside of AWS CloudWatch. Repeat this command until you do or continue the lab if you don't want to wait.
+
[source,sh,role=execute]
----
aws logs describe-log-groups --log-group-name-prefix rosa-${GUID}
----
+
.Sample Output
[source,json,options=nowrap]
----
{
    "logGroups": [
        {
            "logGroupName": "rosa-fxxj9.audit",
            "creationTime": 1682098364311,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:us-east-2:511846242393:log-group:rosa-fxxj9.audit:*",
            "storedBytes": 0
        },
        {
            "logGroupName": "rosa-fxxj9.infrastructure",
            "creationTime": 1682098364399,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:us-east-2:511846242393:log-group:rosa-fxxj9.infrastructure:*",
            "storedBytes": 0
        }
    ]
}
----

Congratulations!

You've successfully forwarded your cluster's logs to the AWS CloudWatch service. We will use this in a later section of the lab.