:markup-in-source: verbatim,attributes,quotes

== Create an admin user for quick access

If you want to be able to access your cluster immediately through a cluster-admin user, you can follow these steps.

This is good if you need quick access to the cluster, which is great for this workshop.

Though the recommended approach is to use a formal identity provider to access the cluster (and then grant that user admin privileges, if desired).

. Run this command to create the admin user. It will also save the output to a file called 'rosa-login.cmd' so that your cluster login information is saved locally for convenience (Don't do that in non-demo environments!)
+
[source,sh,role=execute]
----
rosa create admin --cluster rosa-${GUID} |tee rosa-login.cmd
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
I: Admin account has been added to cluster 'rosa-4fgbq'.
I: Please securely store this generated password. If you lose this password you can delete and recreate the cluster admin user.
I: To login, run the following command:

   oc login https://api.rosa-4fgbq.qrdf.p1.openshiftapps.com:6443 --username cluster-admin --password cD4xo-AnanH-DvB6L-6yndM

I: It may take several minutes for this access to become active.
----
+
[TIP]
====
*Make sure to use the entire password when copying and pasting the command!*
====

. Log into to your cluster by copying the command outputted in the step above and press enter.
+
.Sample Output
[source,texinfo,options=nowrap]
----

Login successful.

You have access to 101 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
Welcome! See 'oc help' to get started.
----
+
[TIP]
====
If you get an error that the *Login failed (401 Unauthorized)* wait a minute and then try again. It takes a few minutes for the cluster authentication operator to update itself after creating the cluster admin user.
====

. To check that you are logged in as the admin user you can run `oc whoami`:
+
[source,sh,role=execute]
----
oc whoami
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
cluster-admin
----

. You can now use the cluster as an admin user, which will suffice for this workshop. Though, for any other use, it is highly recommended to set up an IdP.

=== Login to the OpenShift Web Console

[NOTE]
====
It will take a bit longer for the OpenShift web console to become available.  So instead of waiting, proceed with the lab and return to this section a bit later. 
====

Let's log in to the OpenShift Web Console. To do so, follow the below steps:

. First, we'll need to grab your cluster's web console URL. To do so, run the following command:
+
[source,sh,role=execute]
----
oc whoami --show-console
----
+
.Sample Output
[source,text,options=nowrap]
----
https://console-openshift-console.%rosa_subdomain_base%
----

. If the URL does not look like the above (e.g., begins with `https://api.rosa`) then it is not yet ready, so wait a few more minutes.
. Next, open the printed URL in a web browser.
. Click on the `htpasswd` identity provider.
. Enter the username (`cluster-admin`) and the password from the previous section.
. Feel free to explore the web console.
+
Congratulations! You're now logged into the cluster and ready to move on to the workshop content.
