= Deploy your cluster

In this section we will deploy a ROSA cluster using Hosted Control Plane (HCP).  

In short, with ROSA HCP you can decouple the control plane from the data plane (workers).  This is a new deployment model for ROSA in which the control plane is hosted in a Red Hat owned AWS account.  Therefore the control plane is no longer hosted in your AWS account thus reducing your AWS infrastructure expenses. The control plane is dedicated to a single cluster and is highly available. See the documentation for more about https://docs.openshift.com/container-platform/4.12/architecture/control-plane.html#hosted-control-planes-overview_control-plane[Hosted Control Planes].

[NOTE]
====
As of this writing Hosted Control Planes (HCP) is currently a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. 
====

== Prerequisites

ROSA HCP requires two things to be created before deploying the cluster:

. VPC - This is a "BYO VPC" model
. OIDC configuration

Let's create those first.

=== VPC

. Create the VPC. For this workshop, there is a script provided that will create the VPC and its required components for you. It will use the region configured for the `aws` cli.
+
Please feel free to read it first, or live on the edge and just run it.
+
[source,sh,role=execute]
----
curl https://raw.githubusercontent.com/openshift-cs/rosaworkshop/master/rosa-workshop/rosa/resources/setup-vpc.sh | bash
----
+
See the https://docs.openshift.com/rosa/rosa_planning/rosa-sts-aws-prereqs.html#rosa-vpc_rosa-sts-aws-prereqs[documentation] for more about VPC requirements.

. There are two commands that are outputted from the script. Set those as environment variables to make running the create cluster command easier. Copy them from the output and run them.
+
[source,sh]
----
export PUBLIC_SUBNET_ID=<public subnet id here>
export PRIVATE_SUBNET_ID=<private subnet id here>
----

. Confirm that the environment variables are, in fact, set.
+
[source,sh,role=execute]
----
echo "Public Subnet: $PUBLIC_SUBNET_ID"; echo "Private Subnet: $PRIVATE_SUBNET_ID"
----
+
.Sample Output
[source,text]
----
Public Subnet: subnet-0faeeeb0000000000
Private Subnet: subnet-011fe340000000000
----
+
[WARNING]
====
If one, or both, are blank do not proceed and ask for assistance.
====


=== OIDC Configuration

To create the OIDC configuration to be used in this workshop, run the following command.  We are opting for the automatic mode as this is simpler for the workshop purposes as well as for it to be Red Hat managed. We are also going to store the OIDC ID to an environment variable for later use.

[source,sh,role=execute]
----
export OIDC_ID=$(rosa create oidc-config --mode auto --managed --yes -o json | jq -r '.id'); echo $OIDC_ID;
----
+
.Sample Output
[source,texinfo]
----
23o3doeo86adgqhci4jl000000000000
----


== Create the cluster
Since this is the first time you are deploying ROSA in this account and have not yet created the account roles, then create the account-wide roles and policies, including Operator policies.

. Run the following command to create the account-wide roles:
+
[source,sh,role=execute]
----
rosa create account-roles --mode auto --yes
----

. Run the following command to create the cluster:
+
[source,sh,role=execute]
----
rosa create cluster --cluster-name rosa-${GUID} \
    --subnet-ids ${PUBLIC_SUBNET_ID},${PRIVATE_SUBNET_ID} \
    --hosted-cp \
    --oidc-config-id $OIDC_ID \
    --sts --mode auto --yes
----
+
In about 10 minutes the control plane and API will be up, and about 5-10 minutes after, the worker nodes will be up and the cluster will be completely usable.  This cluster will have 3 Control Plane nodes in a Red Hat AWS account dedicated to your cluster and will also create 2 worker nodes in your AWS account.

== Check installation status
. You can run the following command to check the detailed status of the cluster:
+
[source,sh,role=execute]
----
rosa describe cluster --cluster rosa-${GUID}
----
+
or, you can also watch the logs as it progresses:
+
[source,sh,role=execute]
----
rosa logs install --cluster rosa-${GUID} --watch
----

. Once the state changes to “ready” your cluster is now installed. It may take a few more minutes for the worker nodes to come online. In total this should take about 15 minutes.